spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
#    url: jdbc:postgresql://localhost:32769/monitoring-service
#    username: postgres
#    password: postgres
twitter4j:
  debug: true
  oauth:
    consumer-key:
    consumer-secret:
    access-token:
    access-token-secret:
