spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

twitter4j:
  debug: true
  oauth:
    consumer-key:
    consumer-secret:
    access-token:
    access-token-secret:
