spring:
  datasource:
    url: jdbc:postgresql://localhost:32770/monitoring-service
    username: postgres
    password: postgres

twitter4j:
  debug: true
  oauth:
    consumer-key:
    consumer-secret:
    access-token:
    access-token-secret:
